// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/xdorro/golang-grpc-base-project/internal/handler"
	"github.com/xdorro/golang-grpc-base-project/internal/repo"
	"github.com/xdorro/golang-grpc-base-project/internal/repo/permission_repo"
	"github.com/xdorro/golang-grpc-base-project/internal/repo/role_repo"
	"github.com/xdorro/golang-grpc-base-project/internal/repo/user_repo"
	"github.com/xdorro/golang-grpc-base-project/internal/server"
	"github.com/xdorro/golang-grpc-base-project/internal/service"
	"github.com/xdorro/golang-grpc-base-project/internal/service/auth_service"
	"github.com/xdorro/golang-grpc-base-project/internal/service/permission_service"
	"github.com/xdorro/golang-grpc-base-project/internal/service/role_service"
	"github.com/xdorro/golang-grpc-base-project/internal/service/user_service"
	"github.com/xdorro/golang-grpc-base-project/internal/validator"
	"github.com/xdorro/golang-grpc-base-project/pkg/client"
	"github.com/xdorro/golang-grpc-base-project/pkg/redis"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func initializeServer(ctx context.Context, log *zap.Logger) (*server.Server, error) {
	entClient := client.NewClient(ctx, log)
	userPersist := user_repo.NewRepo(ctx, entClient, log)
	rolePersist := role_repo.NewRepo(ctx, entClient, log)
	permissionPersist := permission_repo.NewRepo(ctx, entClient, log)
	repoRepo := &repo.Repo{
		Client:            entClient,
		UserPersist:       userPersist,
		RolePersist:       rolePersist,
		PermissionPersist: permissionPersist,
	}
	universalClient := redis.NewRedis(log)
	handlerHandler := handler.NewHandler(log, repoRepo, universalClient)
	interceptor := server.NewInterceptor(log, repoRepo, universalClient, handlerHandler)
	grpcServer := server.NewGRPCServer(log, interceptor)
	serveMux := server.NewHTTPServer()
	validatorValidator := validator.NewValidator(log, repoRepo)
	userService := user_service.NewService(log, repoRepo, validatorValidator, handlerHandler, grpcServer)
	authService := auth_service.NewService(log, repoRepo, universalClient, validatorValidator, grpcServer, handlerHandler)
	roleService := role_service.NewService(log, repoRepo, universalClient, validatorValidator, grpcServer)
	permissionService := permission_service.NewService(log, repoRepo, universalClient, validatorValidator, grpcServer)
	serviceService := &service.Service{
		UserService:       userService,
		AuthService:       authService,
		RoleService:       roleService,
		PermissionService: permissionService,
	}
	serverServer, err := server.NewServer(ctx, log, repoRepo, universalClient, grpcServer, serveMux, serviceService)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
