// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/xdorro/golang-grpc-base-project/internal/handler"
	"github.com/xdorro/golang-grpc-base-project/internal/repo"
	"github.com/xdorro/golang-grpc-base-project/internal/server"
	"github.com/xdorro/golang-grpc-base-project/internal/service"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func initializeServer(ctx context.Context, log *zap.Logger) server.IServer {
	iRepo := repo.NewRepo(ctx, log)
	iHandler := handler.NewHandler(ctx, log, iRepo)
	iService := service.NewService(log, iRepo, iHandler)
	iServer := server.NewServer(ctx, log, iRepo, iService)
	return iServer
}
