// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/xdorro/golang-grpc-base-project/internal/server"
)

// Injectors from wire.go:

func initServer(opts ...server.Option) server.IServer {
	iServer := server.NewServer(opts...)
	return iServer
}
